### PR TITLE
Ar register

### PR DESCRIPTION
**Pull request by arumsey93**

### CODE REVIEW

**Comment by TylerCarpenter92** [comment]
SHAME!!!

**Comment by DannyBarker** [comment]
👍

**Comment by arumsey93** [comment]
really @DannyBarker?  railroading at the finest.

**Comment by TylerCarpenter92** [comment]
SHAME ON DANNY!

**Comment by arumsey93** [comment]
#railroaded #trainwreck

**Comment by DannyBarker** [comment]
Didn't know if y'all already knew, but new master

**Pull request merged**
